### ISSUE TITLE
GEX and CNA objects

### ISSUE THREAD

**Issue by jccostel** [Syksy/curatedPCaData#12]
Currently we report only CNA and GEX in the MAE object, but we should have more specific information on what those CNA and GEX tables actually are.  That is, CNA can be log ratio or gistic calls. GEX can be raw, normalized, z-score transformed. We should add that into the name. Instead of "gex" we should have "gex_zscore" or "gex_affy" or something similar.

**Comment by Syksy** [comment]
GEX and CNA data now have more detailed slot names (such as 'gex.rma', 'gex.logq', 'gex.relz', or 'cna.logr', 'cna.gistic') in all datasets.
