### ISSUE TITLE
CNA calls

### ISSUE THREAD

**Issue by jccostel** [Syksy/curatedPCaData#13]
We should have the data in more ready to use format. Gistic calls (-2,-1,0,1,2) are much more usable than log ratios.  Can we  have a conversion or a way to take the "raw" log ratios into discrete calls? I know we talked about keep the data as raw and reproducible as possible, but these data are just not as usable.

**Comment by Syksy** [comment]
All CNA-datasets now have GISTIC or GISTIC-like calls instead of log-ratios.
