### ISSUE TITLE
Package fails to build

### ISSUE THREAD

**Issue by varsha090597** [Syksy/curatedPCaData#16]
I merged my branch with the master and tried checking whether the package builds fine, and it does not. This is the error. Should look into the description file.
<img width="833" alt="Screen Shot 2021-06-02 at 11 39 09 AM" src="https://user-images.githubusercontent.com/61675674/120510368-5a749580-c397-11eb-8e67-6dd4c8244d88.png">

**Comment by varsha090597** [comment]
It is because a comma is missing after those package names in the description file.
<img width="749" alt="Screen Shot 2021-06-02 at 11 59 14 AM" src="https://user-images.githubusercontent.com/61675674/120513136-f6070580-c399-11eb-8307-f4076d9899bf.png">

**Comment by Syksy** [comment]
Hi Varsha,
in the main master branch the comma was there, I'm thinking maybe the dependency edits were pushed in some commit that was missing in your merge due to conflicts. But now your DESCRIPTION seems to be same as the master branch based on the screenshot.
