### ISSUE TITLE
Purity Estimates

### ISSUE THREAD

**Issue by jccostel** [Syksy/curatedPCaData#19]
Here is a reference to an older paper that did some benchmarking with TCGA for ABSOLUTE, ESTIMATE, and LUMP: https://www.nature.com/articles/ncomms9971

We can use this to help define methods and performance

**Comment by Syksy** [comment]
Some handy additional references:

https://ascopubs.org/doi/full/10.1200/PO.20.00016
(comparison to pathologists' purity, Svitlana involved)

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0597-x/tables/1
(table for comparing purity estimation from RNA from 2015, from ISOpure method paper)

**Comment by Syksy** [comment]
For now, the self-estimated purity estimates will not be part of the initial package version 1.0 freeze. Estimates provided by the original authors will be available within the study metadata.
