### ISSUE TITLE
Benchmarking description

### ISSUE THREAD

**Issue by ACSoupir** [Syksy/curatedPCaData#24]
reading through noticed that the https://github.com/Syksy/curatedPCaData/blob/master/data-raw/benchmarking.R says that OSF is still included though I think it was removed? Don't know if i can edit text but minor change

**Comment by Syksy** [comment]
benchmarking.R has been cleaned up (legacy code by Varsha); it's now been removed. We're using GDC processed TCGA data and no longer any of the OSF processed TCGA data.
