### ISSUE TITLE
Fusion status

### ISSUE THREAD

**Issue by MikeOrman** [Syksy/curatedPCaData#29]
ERG fusion status missing from primary datasets: TCGA, Barbieri, and Baca. (Package version = 0.7.3)

I manually added the fusion status for TCGA (excel doc attached). These annotations were found in the supplementary section of the publication page [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4695400/] (url), but seemed to be missing from the cBio link.

Also - NA values are present in the Taylor fusion status data...I'm guessing these samples lacked fusion status data in the original publication.

[TCGA sample annotations.xlsx](https://github.com/Syksy/curatedPCaData/files/7878049/TCGA.sample.annotations.xlsx)

**Comment by Syksy** [comment]
TCGA had differing clinical features (such as ERG fusion statuses) available depending if the TCGA N=333 or the larger N=500ish subset was queried from cBio. These most important fields should now be combined from querying these two datasets and then combining them.

Basicly the difference you'd see when observing the columns at:
https://www.cbioportal.org/study/clinicalData?id=prad_tcga
and
https://www.cbioportal.org/study/clinicalData?id=prad_tcga_pub
... which now complement each other in version 0.7.6.
