### ISSUE TITLE
CNA and fusion sample size different in TCGA

### ISSUE THREAD

**Issue by MikeOrman** [Syksy/curatedPCaData#30]
The CNA data (n=481) and fusion status data (n=495) have different sample sizes. This makes certain operations hard to perform, such as subsetting CNA profiles by fusion status:

``` {r}
TCGA <- curatedPCaData::mae_tcga
TCGA.CNA <- as.data.frame(TCGA@ExperimentList@listData$cna.gistic)
TCGA.CNA.fusion.pos <- TCGA.CNA[,(TCGA@colData@listData$ERG_fusion_GEX == 1)]
TCGA.CNA.fusion.neg <- TCGA.CNA[,(TCGA@colData@listData$ERG_fusion_GEX == 0)]
```
Tested v.0.7.6

**Comment by Syksy** [comment]
The ERG fusion status has been determined using gene expression; for some samples, only gene expression has been determined, while for others copy number alterations are available. We don't have full coverage over all omics.

MultiAssayExperiment does support operations that do pick samples that have information available; using some of the MAE-object functionality may prove useful: https://www.bioconductor.org/packages/devel/bioc/vignettes/MultiAssayExperiment/inst/doc/QuickStartMultiAssay.html

I'm yet to explore all of the options myself, but they seem to have covered it rather nicely. If there are some samples which should have CNA data but don't have it in the MAE-object, then those we can try fill - but it can also be that GDC (where we pull GEX and CNA data from) never processed them.

**Comment by MikeOrman** [comment]
Awesome, i'll take a closer look at the vignette. Thank you for the clarification!
