### ISSUE TITLE
colData does not work for MAE Barwick

### ISSUE THREAD

**Issue by varsha090597** [Syksy/curatedPCaData#34]
The colData argument to access clinical results in an error for the Barwick MAE which needs to be fixed
<img width="1128" alt="Screen Shot 2022-04-07 at 1 55 51 PM" src="https://user-images.githubusercontent.com/61675674/162285676-9f013ed5-18c2-4e0f-b612-e70f0030c2a1.png">

**Comment by Syksy** [comment]
Thanks! For some reason the ```mae_barwick@colData``` had become corrupted along the way.
As of version v0.8.4 the new Barwick MAE object should function correctly again.
