### ISSUE TITLE
script data mismatch

### ISSUE THREAD

**Issue by jhcreed** [Syksy/curatedPCaData#4]
Curation script for GSE25136 does not match clinical data for GSE25136. Most likely an error in the naming process.

**Comment by jhcreed** [comment]
For the Taylor et al. data (GSE21032) - using GEOquery contains mismatched information in the phenotype data. I have posted looking for help 

https://community.rstudio.com/t/geoquery-getgeo-gse21032-pheno-data-mix-up/67546

**Comment by Syksy** [comment]
Taylor et al. is now curated from the two differing GEO instances (one for GEX, one for CNA), complemented by the mutation calls pulled for cBioPortal along with additional clinical information. sampleMap-function for the mae_taylor will contain mappings of IDs between differing platforms.
