### ISSUE TITLE
List of methods/packages for downstream processing and appending to corresponding fields in pData

### ISSUE THREAD

**Issue by Syksy** [Syksy/curatedPCaData#8]
**Methods with R-packages in GitHub/CRAN/BioConductor**

[xCell - cell types enrichment analysis](https://github.com/dviraran/xCell)
_xCell is a webtool that performs cell type enrichment analysis from gene expression data for 64 immune and stroma cell types._
Data type required: RNA expression
Output: Tumor purity / cell composition
Notes: Perhaps better used via wrapper 'immunedeconv'

- [x]  TCGA
- [x]  Taylor et al.
- [x]  Sun et al.

[DeMix](https://github.com/wwylab/DeMix)
_Deconvolution models for mixed transcriptomes from heterogeneous tumor samples with two or three components using expression data from RNAseq or microarray platforms._
Data type required: RNA expression
Output: Tumor purity / cell composition
Notes: -
 
- [x]  TCGA
- [x]  Taylor et al.
- [ ]  Sun et al.

[MCPcounter](https://github.com/ebecht/MCPcounter)
_Estimating the population abundance of tissue-infiltrating immune and stromal cell populations using gene expression_
Data type required: RNA expression
Output: Cell populations
Notes: Perhaps better used via wrapper 'immunedeconv'

- [x] ?

[EPIC](https://github.com/GfellerLab/EPIC)
_Package implementing EPIC method to estimate the proportion of immune, stromal, endothelial and cancer or other cells from bulk gene expression data._ 
Data type required: Bulk RNA expression
Output:
Notes: Perhaps better used via wrapper 'immunedeconv'

- [x] ?

[deconstructSigs](https://github.com/raerose01/deconstructSigs) (?)
_deconstructSigs aims to determine the contribution of known mutational processes to a tumor sample._
Data type required: SNP or similar mutation data
Output: Known mutational processes
Notes: COSMIC v3.1 mutational signature database has to be incorporated manually to deconstructSigs.

- [ ] TCGA

[ABSOLUTE](https://software.broadinstitute.org/cancer/cga/absolute_run) (?)
_ABSOLUTE can estimate purity/ploidy, and from that compute absolute copy-number and mutation multiplicities._
Data type required: HAPSEG file or a segmentation file
Output: Tumor purity
Notes:

- [ ] TCGA

AR activity score methods
Notes: multiple possibilities, e.g. Hieronimus, et al.

- [ ] ?

[immunedeconv](https://github.com/icbi-lab/immunedeconv)
_an R package for unified access to computational methods for estimating immune cell fractions from bulk RNA sequencing data._
Data type required: Method-dependent GEX
Output: Immune decomposition
Notes: Wrapper package for methods quantiseq, timer, cibersort, cibersort_abs, mcp_counter, xcell, epic

- [x] TCGA
- [x] Taylor et al.
- [x] Sun et al.

**Methodology outside R**

[pVACtools / NetMHCPan](https://github.com/griffithlab/pVACtools) (?)
_Neoantigen load_
Data type required: MAF
Output: Neoantigen load
Notes: Written in Python. Set up in Jim's cluster.

- [ ] TCGA

[CIBERSORT](https://cibersort.stanford.edu/)
_Estimation of the abundances of member cell types in a mixed cell population, using gene expression data._
Data type required: RNA expression
Output: 
Notes: Behind registration wall

- [x] ?

[quanTIseq](https://icbi.i-med.ac.at/software/quantiseq/quantiseq.shtml)
_Quantifying tumor-infiltrating immune cells from RNA sequencing data_
Data type required: FASTQ of RNA-seq (?)
Output: Immune cell decomposition
Notes: Docker-image

- [x] ?

**Comment by jhcreed** [comment]
Gene-based risk scores 

- [x] Prolaris
- [x] Oncotype DX
- [x] Decipher 

Alternative risk assessments ? 
- [ ] CAPRA
- [ ] D'Amico
- [ ] ... any others ?

**Comment by Syksy** [comment]
Given the current nature and stage of the package, these options have largely been exhausted and the checklists are no longer up-to-date.
